version: 0.2

phases:
  install: 
    commands:
      - npm install -g snyk
      - snyk auth $SNYK_TOKEN
     # Snyk test -- Ignore Exit codes for demonstration 
      - snyk test --severity-threshold=high --fail-on=upgradable || true
      - snyk code test || true
      - snyk monitor
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
artifacts:
  files:
    - target/dvja-1.0-SNAPSHOT.war
